In [1]:
import torch
import torch.nn as nn

In [2]:
batch_size = 2
one_hot_size = 10
sequence_width = 7
data = torch.randn(batch_size, one_hot_size, sequence_width)
conv1 = nn.Conv1d(in_channels=one_hot_size, out_channels=16, kernel_size=3)
intermediate1 = conv1(data)
print(data.size())
print(intermediate1.size())

torch.Size([2, 10, 7])
torch.Size([2, 16, 5])


In [3]:
data

tensor([[[ 1.1881, -0.0098, -0.4665,  1.0271, -0.5597,  1.3551, -0.3146],
         [ 1.8837, -0.2360,  1.2758, -0.3922, -0.4717, -0.5314,  0.0890],
         [-0.4594, -0.5731, -0.9494, -2.3085, -0.7038, -0.3430,  0.0488],
         [ 1.3257, -1.0915, -2.0863,  1.3237, -0.2543,  0.6256,  0.6527],
         [ 0.2598,  0.0744, -0.6150,  0.8488, -1.2929,  1.5263,  0.1725],
         [-0.8364, -0.4555,  0.1173, -1.4135,  0.4523,  0.7380,  0.5549],
         [-0.1443,  0.5518, -1.4701,  0.6159, -1.0530, -1.1357, -0.7159],
         [-0.4594, -0.6132, -0.4918,  2.2307,  0.1095, -1.6415, -0.0141],
         [ 0.2816,  0.5768,  0.2093,  0.5573, -0.5000, -1.5479,  0.6019],
         [-0.8662, -0.2324, -1.4904, -0.1476,  0.0921,  0.4238,  0.5501]],

        [[-1.0116,  0.5911,  0.0997, -0.9522,  1.1338, -0.9703, -0.9636],
         [ 1.3885, -0.9974, -0.0055,  1.0644,  0.6781,  0.0886, -0.7404],
         [ 0.5978, -0.0266,  0.7403,  0.0279,  0.9494, -1.1366, -1.7089],
         [ 0.2782,  2.8000, -0.4285,

In [4]:
intermediate1

tensor([[[-0.2878, -0.6634,  0.7168, -0.7180,  0.3351],
         [-0.2663, -0.5675,  0.3615,  0.4570,  0.4321],
         [ 0.4049,  0.3189,  0.9617,  0.9699,  0.1957],
         [-0.6105,  0.1543,  0.5739, -0.9096,  0.0588],
         [ 0.6927,  0.6433,  0.6291, -0.1188,  0.1595],
         [-0.5925,  0.7972,  0.0128,  0.5216,  0.9036],
         [ 0.6139, -0.0413, -0.0286,  0.1586,  0.1535],
         [-0.1650, -0.6966, -0.9187, -0.4853, -0.0433],
         [ 0.3006,  0.6234, -0.5312, -0.0454,  0.1742],
         [ 0.3372, -0.2361, -0.9374,  0.3864, -0.7923],
         [ 0.3091, -1.1711,  0.2221, -0.4289, -0.5723],
         [-0.3691,  0.0919,  1.3925,  0.2970,  0.7622],
         [-0.4142, -0.2696,  0.2470, -0.2032,  0.1205],
         [ 0.0676,  0.1205, -0.4738,  0.4441,  0.1110],
         [ 0.5274,  0.0281, -0.1670,  1.0676, -0.3701],
         [ 1.0122, -0.0464,  0.1191, -0.2830, -0.2394]],

        [[-0.0796, -0.3633,  0.3548, -0.1440,  0.1687],
         [ 0.1475, -0.0593, -0.3218, -0.3093, 

In [5]:
conv2 = nn.Conv1d(in_channels=16, out_channels=32, kernel_size=3)
conv3 = nn.Conv1d(in_channels=32, out_channels=64, kernel_size=3)
intermediate2 = conv2(intermediate1)
intermediate3 = conv3(intermediate2)
print(intermediate2.size())
print(intermediate3.size())

torch.Size([2, 32, 3])
torch.Size([2, 64, 1])


In [6]:
y_output = intermediate3.squeeze()
print(y_output.size())

torch.Size([2, 64])


In [7]:
# Method 2 of reducing to feature vectors
print(intermediate1.view(batch_size, -1).size())
# Method 3 of reducing to feature vectors
print(torch.mean(intermediate1, dim=2).size())
# print(torch.max(intermediate1, dim=2).size())
# print(torch.sum(intermediate1, dim=2).size())

torch.Size([2, 80])
torch.Size([2, 16])


In [8]:
intermediate1.size()

torch.Size([2, 16, 5])

In [9]:
print(torch.mean(intermediate1, dim=-1).size())

torch.Size([2, 16])


In [10]:
torch.mean(intermediate1, dim=-1)

tensor([[-0.1234,  0.0834,  0.5702, -0.1466,  0.4011,  0.3285,  0.1712, -0.4618,
          0.1043, -0.2485, -0.3282,  0.4349, -0.1039,  0.0539,  0.2172,  0.1125],
        [-0.0127,  0.0098,  0.3390, -0.2696,  0.1636,  0.2970,  0.2601, -0.0492,
         -0.1417,  0.1698,  0.0804,  0.1915,  0.2049,  0.1543,  0.0658,  0.3509]],
       grad_fn=<MeanBackward1>)

In [11]:
torch.mean(intermediate1, dim=2)

tensor([[-0.1234,  0.0834,  0.5702, -0.1466,  0.4011,  0.3285,  0.1712, -0.4618,
          0.1043, -0.2485, -0.3282,  0.4349, -0.1039,  0.0539,  0.2172,  0.1125],
        [-0.0127,  0.0098,  0.3390, -0.2696,  0.1636,  0.2970,  0.2601, -0.0492,
         -0.1417,  0.1698,  0.0804,  0.1915,  0.2049,  0.1543,  0.0658,  0.3509]],
       grad_fn=<MeanBackward1>)